version: "3.7"
services:
  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/jenkins_compose/jenkins_home/workspace/errorshift/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
  front:
    build: /home/ubuntu/jenkins_compose/jenkins_home/workspace/errorshift/frontend
    container_name: front
    expose:
      - "3000"
    environment:
      - TZ=Asia/Seoul
